site_name: Cloud MTA Build Tool
repo_url: https://github.com/SAP/cloud-mta-build-tool
nav:
  - Home: index.md
  - Download And Installation:
      - Download: download.md
      - Make: makefile.md
      - Tools: tools.md
  - Usage: usage.md
  - Migration: migration.md
  - Configuration: configuration.md
  - Contribution:
      - New Module: newmodule.md
      - New Builder: newbuilder.md
      - Process: process.md
  - Support: support.md
  - Tips:
      - Performance: performance.md
  - Roadmap: roadmap.md



theme:
  name: 'material'
  palette:
    primary: 'blue'
edit_uri: edit/master/docs/docs/

