site_name: Cloud MTA Build Tool
repo_url: https://github.com/SAP/cloud-mta-build-tool
nav:
  - Home: doc/index.md
  - Description: doc/description.md
  - Usage: doc/usage.md
  - Makefile: doc/makefile.md
  - Roadmap: doc/roadmap.md
  - Download: doc/download.md

theme:
  name: 'Cayman'
edit_uri: edit/master/docs/docs/


/